version: '3.8'
services:

  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: happyclean
      MYSQL_DATABASE: happyclean
    ports:
      - "3309:3306"
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password

  web-api:
    container_name: web-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql:
  web-api: