spring:
  application:
    name: happyclean
  profiles:
    active: @profileActive@
  datasource:
    url: jdbc:mysql://mysql:3306/happyclean
    username: root
    password: happyclean
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true

server:
  port: 8080
  servlet:
    context-path: /happyclean

spring.mvc.pathmatch.matching-strategy: ant_path_matcher

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.stat: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE