# spring:
#   config:
#     activate:
#       on-profile: dev
#   datasource:
#     url: jdbc:mysql://localhost:3306/happyclean
#     username: root
#     password: 12345
#spring:
#  config:
#    activate:
#      on-profile: dev
#  datasource:
#    url: jdbc:mysql://localhost:3306/happyclean
#    username: root
#    password: 12345
