spring:
  application:
    name: happyclean
  datasource:
    url: jdbc:mysql://happyclean.mysql.database.azure.com/happyclean?enabledTLSProtocols=TLSv1.2
    username: happyclean
    password: Service123
    # url: jdbc:mysql://localhost:3306/happyclean?enabledTLSProtocols=TLSv1.2
    # username: root
    # password: 12345
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true

server:
  port: 8080
  servlet:
    context-path: /happyclean

springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.stat: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
